[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
port = 8000

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
base = "light"
